# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run
        env:
          IS_BUG: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
        run: |
          echo "BUG=${IS_BUG}"
          if [ $IS_BUG2 == "true" ];then OPTIONS=""; else OPTIONS="--cache" fi
          echo "hoge $OPTIONS"
          
