# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run
        env:
          IS_BUG: ${{ fromJSON("{\"true\":1,\"false\":\"\"}")[contains(github.event.pull_request.labels.*.name, 'bug')] }}
        run: |
          echo "BUG=${IS_BUG}"
          echo "hoge $OPTIONS"
          
